defaults:
  - dataset: default
  - train: default
  - eval: default
  - export: default
  - inference: default
  - data_loader: simple
  - model: lthm
  - trackers: azure
  - training_strategy: accelerate
  - _self_

platform: torch
start_time: "${now: %Y%m%dT%H%M%S}"
model_version: "${start_time}"
run_id: "run_${start_time}_${random_chars: 4}"

datestr: '20230811'

model:
# FIXME evaluate the model with logQ correction
#  log_q_config:
#    beta: 1.0
#    nature: 'content'
  product_tower:
    model_init_metadata:
      embedding_module_path: ""
      filesystem_config:
          kind: s3
          s3_bucket_path: 'nykaa-preprod-discovery-data-swamp'
         

dataset:
  filesystem_config:
    kind: s3
    path_template: 'ranjan.balappa/beauty/lthm/date={date}'
    s3_bucket_path: 'nykaa-preprod-discovery-data-swamp'
  train_data_ratio: 1
  val_data_ratio: 1
  train_period_in_days: 1
  val_period_in_days: 1
  train_data_end_date: "${datestr}"
  val_data_start_date: "${datestr}"

data_loader:
  block_size: 1
  max_readers: 12
  shuffle_files: True
  shuffle_data: False
  mini_batch_size: "${eval: 2 ** 4}"
  shuffle_buffer_num_mini_batches: 0
  max_prefetch: 4
  macro_batches_multiples: 3
  pin_memory: False
  bypass_dataloader: True

stats:
  compute_stats: False
  num_bins: 400
  batch_size: "${eval: 2 ** 5}"
  data_ratio: 0.1
  data_loader:
    kind: simple
    block_size: 32
    max_readers: 4
    max_prefetch: 8
    shuffle_data: False
    shuffle_files: False
    mini_batch_size: 1024
    shuffle_buffer_num_mini_batches: 64
    macro_batches_multiples: 3
    pin_memory: False

train:
  num_workers: 4
  batch_size: "${eval: 2 ** 6}"
  validation_steps: 10
  train_metrics_every_n_steps: 10
  val_metrics_every_n_steps: 10
  checkpoint_every_k_steps: 50
  train_steps: 20000  #based on active users
  epochs: 1
  

eval:
  num_workers: 4
  eval_batch_size: "${eval: 2 ** 5}"
  skip_eval: True
  skip_knn_eval: True

inference:
  num_workers: 4
  inference_batch_size: "${eval: 2 ** 5}"
  skip_inference: True

export:
  filesystem_config:
    kind: s3
    s3_bucket_path: 'nykaa-preprod-discovery-data-swamp'
  trace: False
  best_model_after_k_steps: 500
  export_if_loss_within_factor_of_best_model: 1.3
  path_prefix: "lthm_model/dev"
  export_inference_config: True

training_strategy:
  # FIXME stability issues with gradient checkpointing and fp16
  precision: 'no'
  static_graph: True
  timeout: 300  # in seconds
#  broadcast_buffers: False