filesystem_config: ???
exclude_dates: []
train_data_ratio: 1.0
val_data_ratio: 1.0
train_data_end_date: "${day_before_days: 2}"
train_period_in_days: 14
val_data_start_date: "${day_before_days: 1}"
val_period_in_days: 1
path_glob_train: ""
path_glob_test: ""